layout: default
nav_exclude: true
title: VDI WordPress Dev Docs
description: A place for all of the WordPress development documentation!
theme: just-the-docs
color_scheme: vdi
enable_copy_code_button: true

url: https://docs.vincentdevelopment.ca

aux_links:
  Docs for this website: https://just-the-docs.com/
  Repo: https://github.com/Vincent-Design-Inc/vdi-dev-docs

callouts:
  warning:
    title: Warning
    color: red
    opacity: 0.2
  note:
    title: Note
    color: yellow
    opacity: 0.2

mermaid:
  version: "9.1.3"